- hosts: jenkins_server
  # become: yes
  # become_method: sudo
  roles: # ทำให้ ansible รันเฉพาะ tag ได้ถ้าไม่ระบุแท๊กก็จะรันทั้งมด ansible-playbook setup.yml -t docker 
    - {role: docker, tags: "docker"} 
    - {role: elk, tags: "elk"} 
