---
# tasks file for install-jenkins
- name: "Start firewall service"
  become: yes
  become_method: sudo
  service:
    name: firewalld.service
    state: started
    enabled: yes

- name: "ADD Firewall Policty for interface docker0"
  become: yes
  become_method: sudo
  firewalld:
    interface: docker0
    state: enabled
    zone: trusted

- name: "Add permanet firewall Policy"
  become: yes
  become_method: sudo
  firewalld:
    zone: trusted
    state: enabled
    masquerade: "yes"
    permanent: yes

- name: "Reload firewall"
  become: yes
  become_method: sudo
  firewalld:
    zone: trusted
    state: enabled
    immediate: yes

- name: "Restart Docker Service"
  become: yes
  become_method: sudo
  service:
    name: docker
    state: reloaded

- name: Create Docker Network for Jenkins
  docker_network:
    name: jenkins

- name: Create Docker Volume for Jenkins Data
  docker_volume:
    name: jenkins-data
    state: present

- name: Create Docker Volume for Jenkins Certificate TLS
  docker_volume:
    name: jenkins-docker-certs
    state: present

- name: "Install Docker in Docker for Jenkins"
  # become: yes
  # become_method: sudo
  docker_container:
    env:
      DOCKER_TLS_CERTDIR: "/certs"
    name: jenkins-docker
    image: docker:19.03.11-dind
    state: started
    privileged: yes
    networks_cli_compatible: yes
    purge_networks: yes
    published_ports:
      - "2376:2376"
    networks:
      - name: jenkins
        aliases:
         - docker
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client"


- name: "Install Jenkins with Docker"
  docker_container:
    env:
      DOCKER_HOST: "tcp://docker:2376" 
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"
    restart: yes
    restart_policy: always
    name: jenkins-blueocean
    image: jenkinsci/blueocean
    state: started
    purge_networks: yes
    published_ports:
      - "8080:8080"
      - "50000:50000"
    networks_cli_compatible: yes
    networks:
      - name: jenkins
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client:ro"

- name: "Dispaly Jenkins Initial Password"
  command: docker exec -it jenkins-blueocean cat /var/jenkins_home/secrets/initialAdminPassword


