---
# tasks file for install-jenkins
- name: Create Docker Network for Jenkins
  docker_network:
    name: jenkins

- name: Create Docker Volume for Jenkins
  docker_volume:
    name: jenkins-data
    state: present

- name: "Install Docker in Docker for Jenkins"
  become: yes
  become_method: sudo
  docker_container:
    env:
      DOCKER_TLS_CERTDIR: "/certs"
    name: jenkins-docker
    image: docker:19.03.11-dind
    state: started
    privileged: yes
    purge_networks: yes
    published_ports:
      - "2376:2376"
    networks:
      - name: jenkins
        aliases:
         - docker
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "/home/{{ansible_user}}/ssl-certificate:/certs/client:ro"


- name: "Install Jenkins with Docker"
  docker_container:
    env:
      DOCKER_HOST: "tcp://docker:2376" 
      DOCKER_CERT_PATH: "/certs/client"
    restart: yes
    restart_policy: always
    name: jenkins-blueocean
    image: jenkinsci/blueocean
    state: started
    purge_networks: yes
    published_ports:
      - "8080:8080"
    networks_cli_compatible: yes
    networks:
      - name: jenkins
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "/home/{{ansible_user}}/ssl-certificate:/certs/client:ro"

- name: "Dispaly Jenkins Initial Password"
  command: docker exec -it jenkins-blueocean cat /var/jenkins_home/secrets/initialAdminPassword


